changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title:  What's new in this release
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
