-I/usr/include/cjson
-I/usr/include/libnl3
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src/ap
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src/common
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/wpa_supplicant
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src/utils
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src/drivers
-IHOME/usr/include/
-g
-fPIC
-fcommon
-D_GNU_SOURCE
-D_ANSC_LINUX
-D_COSA_INTEL_USG_ATOM_
-DUSE_NOTIFY_COMPONENT
-DCISCO_XB3_PLATFORM_CHANGES
-DFEATURE_ONE_WIFI
-DWIFI_HAL_VERSION_3
-DFEATURE_SUPPORT_PASSPOINT
-DFEATURE_SUPPORT_WEBCONFIG
-DBANANA_PI_PORT
-DNL80211_ACL
-D_PLATFORM_BANANAPI_R4_
-DFEATURE_SINGLE_PHY
-DEASY_MESH_NODE
-DEM_APP
-DONEWIFI_STA_MGR_APP_SUPPORT
-DONEWIFI_EASYCONNECT_APP_SUPPORT
-DONEWIFI_ANALYTICS_APP_SUPPORT
-DONEWIFI_BLASTER_APP_SUPPORT
-DONEWIFI_CAC_APP_SUPPORT
-DONEWIFI_CSI_APP_SUPPORT
-DONEWIFI_HARVESTER_APP_SUPPORT
-DONEWIFI_LEVL_APP_SUPPORT
-DONEWIFI_MOTION_APP_SUPPORT
-DONEWIFI_WHIX_APP_SUPPORT
-DFEATURE_OFF_CHANNEL_SCAN_5G
-DPLATFORM_LINUX
-Wall
-Wextra
-Wno-unused-parameter
-Wno-pointer-sign
-Wno-sign-compare
-Wno-type-limits
-Wno-format-truncation
-Wno-discarded-qualifiers
-Werror=implicit-function-declaration
-Werror=int-conversion
-Werror=incompatible-pointer-types
-Werror=return-type
-Werror=uninitialized
-Werror=maybe-uninitialized
-Werror=format
-Werror=format-security
-Werror=nonnull
-Werror=array-bounds
-Werror=stringop-overflow
-Werror=sizeof-pointer-memaccess
-Werror=vla
-Werror=unused-variable
-Werror=enum-conversion
-Werror=address
-Werror=float-conversion
-DENABLE_FEATURE_MESHWIFI
-DCONFIG_HW_CAPABILITIES
-DNEWPLATFORM_PORT
-DHOSTAPD
-DCONFIG_CRYPTO_INTERNAL
-DCONFIG_DRIVER_NL80211
-DNEED_AP_MLME
-DCONFIG_IEEE80211AC
-DCONFIG_IEEE80211AX
-DCONFIG_IEEE80211N
-DCONFIG_WPS
-DIEEE8021X_EAPOL
-DEAP_SERVER_IDENTITY
-DEAP_SERVER_MD5
-DEAP_SERVER_TLS
-DEAP_SERVER_MSCHAPV2
-DEAP_SERVER_PEAP
-DEAP_SERVER_TTLS
-DCONFIG_ECC
-DRDK_ONEWIFI
-DCONFIG_IEEE80211W
-DCONFIG_OPENSSL_CMAC
-DCONFIG_LIBNL20
-DCONFIG_WNM_AP
-DHOSTAPD_2_11
-DCONFIG_WEP
-DFEATURE_SUPPORT_RADIUSGREYLIST
-DCONFIG_SAE
-DCONFIG_SUITEB192
-DCONFIG_SUITE
-DCONFIG_SUITEB
-DCONFIG_SHA256
-DCONFIG_SHA384
-DCONFIG_SHA512
-DCONFIG_HMAC_SHA384_KDF
-DCONFIG_SME
-DCONFIG_INTERWORKING
-DCONFIG_GAS
-DCONFIG_HS20
-DCONFIG_TESTING_OPTIONS
-DHOSTAPD_DUMP_STATE
-DCONFIG_CTRL_IFACE_UNIX
-DCONFIG_CTRL_IFACE
-DCONFIG_CTRL_IFACE_MIB
-DCONFIG_OCV
-DCONFIG_IEEE80211R
-DCONFIG_IEEE80211R_AP
-DCONFIG_ETH_P_OUI
-DCONFIG_WNM
-DCONFIG_IEEE80211BE
-DCONFIG_MBO
-DNO_SUPPLICANT
-DEAP_SERVER_UNAUTH_TLS
-DEAP_SERVER_GTC
-DEAP_SERVER_PAX
-DEAP_SERVER_PSK
-DEAP_SERVER_SAKE
-DEAP_SERVER_GPSK
-DEAP_GPSK_SHA256
-DEAP_SERVER_PWD
-DEAP_SERVER_WSC
-DCONFIG_WPS_TESTING
-DEAP_SERVER_IKEV2
-DEAP_SERVER_TNC
-DEAP_SERVER
-DPKCS12_FUNCS
-DEAP_TLS_FUNCS
-DCONFIG_TLSV11
-DCONFIG_TLSV12
-DCONFIG_TLS_OPENSSL
-DCRYPTO_RSA_OAEP_SHA256
-DTLS_DEFAULT_CIPHERS=DEFAULT:!EXP:!LOW
-DCONFIG_DES
-DCONFIG_HMAC_SHA256_KDF
-DALL_DH_GROUPS
-DCONFIG_IPV6
-DCONFIG_PROXYARP
-DCONFIG_ACS
-DCONFIG_DEBUG_LINUX_TRACING
-DCONFIG_DEBUG_FILE
-DEAP_TLS
-DEAP_UNAUTH_TLS
-DEAP_PEAP
-DEAP_TTLS
-DEAP_MD5
-DEAP_MSCHAPv2
-DEAP_GTC
-DEAP_OTP
-DEAP_LEAP
-DEAP_PSK
-DEAP_PAX
-DEAP_SAKE
-DEAP_GPSK
-DEAP_PWD
-DCONFIG_GENERIC_MLO
-DCONFIG_MLO
-DPIC
-DKERNEL_6_6
-DCONFIG_AP
-Wno-deprecated-declarations

-Wl,--allow-shlib-undefined
-Wl,--unresolved-symbols=ignore-all
