-I/usr/include/cjson
-I/usr/include/libnl3
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src/ap
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src/common
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/wpa_supplicant
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src/utils
-IHOME/build/rdk-wifi-libhostap/source/hostap-2.11/src/drivers
-IHOME/usr/include/
-g
-fPIC
-fcommon
-DALL_DH_GROUPS
-DCONFIG_ACS
-DCONFIG_AP
-DCONFIG_BSS_LOAD
-DCONFIG_CRYPTO_INTERNAL
-DCONFIG_CTRL_IFACE
-DCONFIG_CTRL_IFACE_UNIX
-DCONFIG_DEBUG_FILE
-DCONFIG_DEBUG_LINUX_TRACING
-DCONFIG_DES
-DCONFIG_DRIVER_AID
-DCONFIG_DRIVER_BRCM
-DCONFIG_DRIVER_BRCM_MAP
-DCONFIG_DRIVER_HOSTAP
-DCONFIG_DRIVER_NL80211
-DCONFIG_EAP
-DCONFIG_EAP_GTC
-DCONFIG_EAP_MD5
-DCONFIG_EAP_MSCHAPV2
-DCONFIG_EAP_PEAP
-DCONFIG_EAP_TLS
-DCONFIG_EAP_TTLS
-DCONFIG_ECC
-DCONFIG_ERP
-DCONFIG_ETH_P_OUI
-DCONFIG_GAS
-DCONFIG_HS20
-DCONFIG_HW_CAPABILITIES
-DCONFIG_IAPP
-DCONFIG_IEEE80211AC
-DCONFIG_IEEE80211AX
-DCONFIG_IEEE80211BE
-DCONFIG_IEEE80211R
-DCONFIG_IEEE80211R_AP
-DCONFIG_IEEE80211W
-DCONFIG_INTERNAL_LIBTOMMATH
-DCONFIG_INTERWORKING
-DCONFIG_IPV6
-DCONFIG_LIBNL32
-DCONFIG_MBO
-DCONFIG_MLO
-DCONFIG_OWE
-DCONFIG_PROXYARP
-DCONFIG_RSN_PREAUTH
-DCONFIG_SAE
-DCONFIG_SHA256
-DCONFIG_SHA384
-DCONFIG_SHA512
-DCONFIG_SME
-DCONFIG_SUITE
-DCONFIG_SUITEB
-DCONFIG_SUITEB192
-DCONFIG_TLSV11
-DCONFIG_TLSV12
-DCONFIG_TPC_REPORT
-DCONFIG_WEP
-DCONFIG_WMM
-DCONFIG_WNM
-DCONFIG_WNM_AP
-DCONFIG_WPS
-DCRYPTO_RSA_OAEP_SHA256
-DEAP_GPSK
-DEAP_GPSK_SHA256
-DEAP_GTC
-DEAP_LEAP
-DEAP_MD5
-DEAP_MSCHAPv2
-DEAP_OTP
-DEAP_PAX
-DEAP_PEAP
-DEAP_PSK
-DEAP_PWD
-DEAP_SAKE
-DEAP_SERVER
-DEAP_SERVER_AKA
-DEAP_SERVER_AKA_PRIME
-DEAP_SERVER_FAST
-DEAP_SERVER_GPSK
-DEAP_SERVER_GPSK_SHA256
-DEAP_SERVER_GTC
-DEAP_SERVER_IDENTITY
-DEAP_SERVER_IKEV2
-DEAP_SERVER_MD5
-DEAP_SERVER_MSCHAPV2
-DEAP_SERVER_PAX
-DEAP_SERVER_PEAP
-DEAP_SERVER_PSK
-DEAP_SERVER_PWD
-DEAP_SERVER_SAKE
-DEAP_SERVER_SIM
-DEAP_SERVER_TEAP
-DEAP_SERVER_TLS
-DEAP_SERVER_TLV
-DEAP_SERVER_TNC
-DEAP_SERVER_TTLS
-DEAP_SERVER_UNAUTH_TLS
-DEAP_SERVER_WSC
-DEAP_TLS
-DEAP_TLS_FUNCS
-DEAP_TTLS
-DEAP_UNAUTH_TLS
-DFEATURE_HOSTAP_MGMT_FRAME_CTRL
-DFEATURE_SUPPORT_PASSPOINT
-DFEATURE_SUPPORT_RADIUSGREYLIST
-DGIT_VERSION_STR_POSTFIX=-hostap_2_11+
-DHAVE_CONFIG_H
-DHOSTAPD
-DHOSTAPD_2_11
-DHOSTAPD_DUMP_STATE
-DIEEE8021X_EAPOL
-DLINUX_PORT
-DNEED_AP_MLME
-DNEWPLATFORM_PORT
-DNL80211_ACL
-DPIC
-DPKCS12_FUNCS
-DPROJECT_IGNITE
-DRDK_ONEWIFI
-DRDK_PORT
-DTLS_DEFAULT_CIPHERS=DEFAULT:!EXP:!LOW
-DWIFI_EMULATOR_CHANGE
-DWIFI_HAL_VERSION_3
-DWPS_SERCOMMXB10_INFO
-DXB10_PORT

-Wall
-Wextra
-Wno-unused-parameter
-Wno-pointer-sign
-Wno-sign-compare
-Wno-type-limits
-Wno-format-truncation
-Wno-discarded-qualifiers
-Werror=implicit-function-declaration
-Werror=int-conversion
-Werror=incompatible-pointer-types
-Werror=return-type
-Werror=uninitialized
-Werror=maybe-uninitialized
-Werror=format
-Werror=format-security
-Werror=nonnull
-Werror=array-bounds
-Werror=stringop-overflow
-Werror=sizeof-pointer-memaccess
-Werror=vla
-Werror=unused-variable
-Werror=enum-conversion
-Werror=address
-Werror=float-conversion
-Wno-deprecated-declarations

-Wl,--allow-shlib-undefined
-Wl,--unresolved-symbols=ignore-all
