#!/usr/bin/env python3
#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2026 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Op-class round-trip check (temporary advisory CI check, from LTE-3093).

For the base and the head HAL tree: takes the op-class code by name from the tree (nothing
is hand-copied), links it with driver.c and one build leg's hostap
src/common/ieee802_11_common.c, and sweeps every country/band/channel/bandwidth through
get_op_class_from_radio_params() and ieee80211_chan_to_freq(). Reports how the broken cases
(BADFREQ: no round trip to the channel's frequency; REJECT: refused by the HAL) differ.

usage: check.py BASE_TREE HEAD_TREE HOSTAP_DIR HALIF_INCLUDE HOSTAPD_VERSION
exit:  0 unchanged, 3 changed, anything else is a mechanism error
"""
import os
import re
import subprocess
import sys
import tempfile
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
CHANGED = 3
UTILS, PRIV = 'src/wifi_hal_nl80211_utils.c', 'src/wifi_hal_priv.h'
# Taken from UTILS in source order. OPTIONAL names are used when present (helpers a PR may
# add or remove); a missing REQUIRED name fails the run as a mechanism error.
REQUIRED = [
    'wifi_country_map',
    'us_op_class_cc', 'eu_op_class_cc', 'jp_op_class_cc', 'cn_op_class_cc',
    'us_op_class', 'eu_op_class', 'jp_op_class', 'cn_op_class', 'other_op_class',
    'get_coutry_str_from_code', 'find_country_code_match', 'get_wifi_op_class_info',
    'get_op_class_from_radio_params',
]
OPTIONAL = [
    'matches_bandwidth_us', 'matches_bandwidth_eu', 'matches_bandwidth_jp',
    'matches_bandwidth_cn', 'matches_bandwidth_global', 'matches_bandwidth_for_country',
    'resolvable_op_class',
]
PRIV_TYPES = [r'typedef struct\s*\{[^{}]*\}\s*wifi_radio_op_class_t\s*;',
              r'typedef struct\s*\{[^{}]*\}\s*wifi_country_radio_op_class_t\s*;',
              r'struct wifiCountryEnumStrMap\s*\{[^{}]*\}\s*;']
PRELUDE = r'''/* GENERATED by check.py -- do not edit */
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include "wifi_hal_generic.h"
#include "wifi_hal_radio.h"

#define ARRAY_SZ(array) (sizeof(array) / sizeof((array)[0]))
#define wifi_hal_dbg_print(...)   ((void)0)
#define wifi_hal_info_print(...)  ((void)0)
#define wifi_hal_error_print(...) ((void)0)

/* hostap: linked from the build leg's src/common/ieee802_11_common.c */
int ieee80211_chan_to_freq(const char *country, unsigned char op_class, unsigned char chan);

'''
BANDS = {'1': '2.4G', '2': '5G', '16': '6G'}                                    # wifi_freq_bands_t
BW = {'1': '20', '2': '40', '4': '80', '8': '160', '16': '80+80', '32': '320'}  # wifi_channelBandwidth_t
BAND_RANK = {band_name: rank for rank, band_name in enumerate(BANDS.values())}


def skip_to_matching_brace(text, pos):
    """text[pos] == '{'; return the index just past its matching '}' (skips strings/comments)."""
    depth = 0
    while pos < len(text):
        char = text[pos]
        if text.startswith('/*', pos):
            pos = text.index('*/', pos) + 2
            continue
        if text.startswith('//', pos):
            pos = text.index('\n', pos)
            continue
        if char in '"\'':
            quote_end = pos + 1
            while text[quote_end] != char:
                quote_end += 2 if text[quote_end] == '\\' else 1
            pos = quote_end + 1
            continue
        depth += {'{': 1, '}': -1}.get(char, 0)
        if char == '}' and depth == 0:
            return pos + 1
        pos += 1
    raise ValueError('unbalanced braces')


def find_definition(text, name):
    """(start, end) of a top-level function or initialized variable called `name`, or None."""
    func = r'^[A-Za-z_][\w \t\*]*?\b' + name + r'\s*\([^;{)]*\)\s*\{'
    var = r'^[A-Za-z_][\w \t\*]*?\b' + name + r'\s*(\[\s*\])?\s*=\s*\{'
    for pattern, is_var in ((func, False), (var, True)):
        match = re.search(pattern, text, re.MULTILINE)
        if match:
            end = skip_to_matching_brace(text, match.end() - 1)
            return match.start(), (text.index(';', end) + 1 if is_var else end)
    return None


def extract(tree):
    """The HAL's op-class selection as one standalone C file."""
    utils = open(f'{tree}/{UTILS}').read()
    priv = open(f'{tree}/{PRIV}').read()
    parts = [PRELUDE]
    for pattern in PRIV_TYPES:
        match = re.search(pattern, priv)
        if not match:
            sys.exit(f'check: {pattern} not found in {PRIV}')
        parts.append(match.group(0) + '\n')
    spans = []
    for name in REQUIRED + OPTIONAL:
        span = find_definition(utils, name)
        if span is None and name in REQUIRED:
            sys.exit(f'check: {name} not found in {UTILS}')
        if span is not None:
            spans.append(span)
    return ''.join(parts + [f'\n{utils[start:end]}\n' for start, end in sorted(spans)])


def sweep(tree, hostap, halif, version):
    """Broken cases of the HAL tree linked with this hostap:
    ({(status, band, bw, channel, cc): detail}, all country codes)."""
    with tempfile.TemporaryDirectory() as work:
        with open(f'{work}/extracted.c', 'w') as out_file:
            out_file.write(extract(tree))
        subprocess.run([
            os.environ.get('CC', 'gcc'), '-std=gnu11', '-w', f'-DHOSTAPD_VERSION={version}',
            f'-I{work}', f'-I{halif}', f'-I{hostap}/src', f'-I{hostap}/src/utils',
            f'{HERE}/driver.c', f'{hostap}/src/common/ieee802_11_common.c', '-o', f'{work}/sweep',
            # hostap's file references helpers (wpabuf, os_*) the sweep never calls
            '-Wl,--unresolved-symbols=ignore-all',
        ], check=True)
        rows = subprocess.run([f'{work}/sweep'], check=True, capture_output=True, text=True).stdout
    pairs, all_ccs = {}, set()
    for row in rows.splitlines():
        status, cc, band, channel, bw, *rest = row.split()
        all_ccs.add(cc)
        if status != 'OK':
            detail = f' op{rest[0]} -> {rest[1]}' if status == 'BADFREQ' else ''
            pairs[(status, BANDS[band], BW[bw], int(channel), cc)] = detail
    return pairs, all_ccs


def countries(ccs, all_ccs):
    """Short, diff-friendly country set: 'ALL', 'ALL except CA US', or 'GR'."""
    if ccs == all_ccs:
        return 'ALL'
    if len(ccs) > len(all_ccs) // 2:
        return 'ALL except ' + ' '.join(sorted(all_ccs - ccs))
    return ' '.join(sorted(ccs))


def render(pairs, all_ccs):
    """{(status, band, bw, channel, cc): detail} -> lines, one per country set and detail,
    listing the channels: 'BADFREQ 5G bw20 op121 -> -1 ch144: ALL except CA CN US'."""
    by_case = defaultdict(set)
    for (status, band, bw, channel, cc), detail in pairs.items():
        by_case[(status, band, bw, channel, detail)].add(cc)
    by_line = defaultdict(list)
    for (status, band, bw, channel, detail), ccs in by_case.items():
        by_line[(status, band, bw, detail, countries(ccs, all_ccs))].append(channel)
    lines = [((BAND_RANK[band], int(bw.split('+')[0]), status, min(chans), detail),
              f'{status} {band} bw{bw}{detail} ch{",".join(map(str, sorted(chans)))}: {who}')
             for (status, band, bw, detail, who), chans in by_line.items()]
    return [line for _key, line in sorted(lines)]


def details(title, lines, expanded):
    if lines:
        print(f'<details{" open" if expanded else ""}><summary>{title}: {len(lines)}</summary>\n')
        print('```\n' + '\n'.join(lines) + '\n```\n</details>\n')


def main(base_tree, head_tree, hostap, halif, version):
    """Markdown report on stdout; exit 0 = mapping unchanged, CHANGED = changed."""
    base, base_ccs = sweep(base_tree, hostap, halif, version)
    head, all_ccs = sweep(head_tree, hostap, halif, version)
    all_ccs |= base_ccs
    changed = {key for key in head.keys() & base.keys() if head[key] != base[key]}
    sections = [  # (title, count label, lines, expanded)
        ('❌ newly broken', 'newly broken',
         render({key: head[key] for key in head.keys() - base.keys()}, all_ccs), True),
        ('🔁 still broken, different op class', 'op class changed',
         render({key: head[key] for key in changed}, all_ccs), True),
        ('✅ no longer broken', 'fixed',
         render({key: base[key] for key in base.keys() - head.keys()}, all_ccs), False),
    ]
    counts = ', '.join(f'{len(lines)} {label}' for _title, label, lines, _open in sections if lines)
    if counts:
        print('> [!CAUTION]')
        print(f'> **Op-class → frequency mapping changed vs the base ({counts}). '
              'This may affect downstream behaviour; make sure it is intended.**\n')
    else:
        print('no change\n')
    for title, _label, lines, expanded in sections:
        details(title, lines, expanded)
    details('all broken cases after this change', render(head, all_ccs), False)
    return CHANGED if counts else 0


if __name__ == '__main__':
    sys.exit(main(*sys.argv[1:6]))
