/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Sweep every (country, band, channel, bandwidth) through the HAL's op-class selection
 * (extracted.inc, generated by check.py) and the linked hostap's ieee80211_chan_to_freq(),
 * the round trip the HAL does in its scan, chandef, CSA and DFS paths. One line per case:
 * "OK|BADFREQ cc band ch bw op freq" if the HAL accepts it, "REJECT cc band ch bw" if not.
 */
#include "extracted.inc"

static int expected_freq(wifi_freq_bands_t band, unsigned int chan)
{
    if (band == WIFI_FREQUENCY_2_4_BAND) {
        return chan == 14 ? 2484 : 2407 + 5 * (int)chan;
    }
    if (band == WIFI_FREQUENCY_5_BAND) {
        return 5000 + 5 * (int)chan;
    }
    return chan == 2 ? 5935 : 5950 + 5 * (int)chan; /* 6 GHz */
}

/* num_bws: how many of bws[] to try (2.4 GHz stops at 40, 320 MHz needs hostap 2.11) */
static void sweep(wifi_countrycode_type_t cc, const char *cc_str, wifi_freq_bands_t band,
    const unsigned int *chans, size_t num_chans, size_t num_bws)
{
    static const wifi_channelBandwidth_t bws[] = { WIFI_CHANNELBANDWIDTH_20MHZ,
        WIFI_CHANNELBANDWIDTH_40MHZ, WIFI_CHANNELBANDWIDTH_80MHZ, WIFI_CHANNELBANDWIDTH_160MHZ,
        WIFI_CHANNELBANDWIDTH_80_80MHZ, WIFI_CHANNELBANDWIDTH_320MHZ };

    for (size_t chan_idx = 0; chan_idx < num_chans; chan_idx++) {
        for (size_t bw_idx = 0; bw_idx < num_bws; bw_idx++) {
            wifi_radio_operationParam_t param;
            unsigned int chan = chans[chan_idx];

            memset(&param, 0, sizeof(param));
            param.band = band;
            param.channel = chan;
            param.channelWidth = bws[bw_idx];
            param.countryCode = cc;

            int op = get_op_class_from_radio_params(&param);
            if (op <= 0) {
                printf("REJECT %s %d %u %d\n", cc_str, band, chan, bws[bw_idx]);
                continue;
            }
            int freq = ieee80211_chan_to_freq(cc_str, (unsigned char)op, (unsigned char)chan);
            printf("%s %s %d %u %d %d %d\n", freq == expected_freq(band, chan) ? "OK" : "BADFREQ",
                cc_str, band, chan, bws[bw_idx], op, freq);
        }
    }
}

int main(void)
{
    static const unsigned int ch24[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };
    static const unsigned int ch5[] = { 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116,
        120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165, 169, 173, 177 };
    unsigned int ch6[60] = { 2 };
    size_t num_ch6 = 1;

    for (unsigned int chan = 1; chan <= 233; chan += 4) {
        ch6[num_ch6++] = chan;
    }
    for (size_t idx = 0; idx < ARRAY_SZ(wifi_country_map); idx++) {
        wifi_countrycode_type_t cc = wifi_country_map[idx].countryCode;
        char cc_str[8] = { 0 };

        get_coutry_str_from_code(cc, cc_str);
        sweep(cc, cc_str, WIFI_FREQUENCY_2_4_BAND, ch24, ARRAY_SZ(ch24), 2);
        sweep(cc, cc_str, WIFI_FREQUENCY_5_BAND, ch5, ARRAY_SZ(ch5), 5);
        sweep(cc, cc_str, WIFI_FREQUENCY_6_BAND, ch6, num_ch6, HOSTAPD_VERSION >= 211 ? 6 : 5);
    }
    return 0;
}
