#!/usr/bin/env python3
#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2026 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Pull the HAL's op-class / regulatory code out of rdk-wifi-hal into one standalone C file.

Definitions are taken by name from the live sources, in source order, so the test always
exercises what the PR actually ships (nothing is hand-copied, nothing can drift).

usage: extract.py HAL_TREE OUT.c
"""
import re
import sys

UTILS = 'src/wifi_hal_nl80211_utils.c'
PRIV = 'src/wifi_hal_priv.h'

# Data + functions the op-class selection depends on. OPTIONAL names are extracted when
# present (helpers a PR may add/remove); everything else must exist or extraction fails.
REQUIRED = [
    'wifi_country_map',
    'us_op_class_cc', 'eu_op_class_cc', 'jp_op_class_cc', 'cn_op_class_cc',
    'us_op_class', 'eu_op_class', 'jp_op_class', 'cn_op_class', 'other_op_class',
    'get_coutry_str_from_code', 'find_country_code_match', 'get_wifi_op_class_info',
    'get_op_class_from_radio_params',
]
OPTIONAL = [
    'matches_bandwidth_us', 'matches_bandwidth_eu', 'matches_bandwidth_jp',
    'matches_bandwidth_cn', 'matches_bandwidth_global', 'matches_bandwidth_for_country',
    'resolvable_op_class',
]
PRIV_TYPES = ['wifi_radio_op_class_t', 'wifi_country_radio_op_class_t']

PRELUDE = r'''/* GENERATED by extract.py from {tree} -- do not edit */
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include "wifi_hal_generic.h"
#include "wifi_hal_radio.h"

#define ARRAY_SZ(x) (sizeof(x) / sizeof((x)[0]))
#define wifi_hal_dbg_print(...)   ((void)0)
#define wifi_hal_info_print(...)  ((void)0)
#define wifi_hal_error_print(...) ((void)0)

/* hostap: linked from the build leg's src/common/ieee802_11_common.c */
int ieee80211_chan_to_freq(const char *country, unsigned char op_class, unsigned char chan);

'''


def skip_to_matching_brace(text, pos):
    """text[pos] == '{'; return the index just past its matching '}' (skips strings/comments)."""
    depth, length = 0, len(text)
    while pos < length:
        char = text[pos]
        if text.startswith('/*', pos):
            pos = text.index('*/', pos) + 2
            continue
        if text.startswith('//', pos):
            pos = text.index('\n', pos)
            continue
        if char in '"\'':
            quote_end = pos + 1
            while text[quote_end] != char:
                quote_end += 2 if text[quote_end] == '\\' else 1
            pos = quote_end + 1
            continue
        if char == '{':
            depth += 1
        elif char == '}':
            depth -= 1
            if depth == 0:
                return pos + 1
        pos += 1
    raise ValueError('unbalanced braces')


def find_definition(text, name):
    """(start, end) of a top-level function or initialized variable called `name`."""
    func = re.compile(r'^[A-Za-z_][\w \t\*]*?\b' + name + r'\s*\([^;{)]*\)\s*\{', re.MULTILINE)
    var = re.compile(r'^[A-Za-z_][\w \t\*]*?\b' + name + r'\s*(\[\s*\])?\s*=\s*\{', re.MULTILINE)
    for pattern, is_var in ((func, False), (var, True)):
        match = pattern.search(text)
        if match:
            end = skip_to_matching_brace(text, match.end() - 1)
            if is_var:
                end = text.index(';', end) + 1
            return match.start(), end
    return None


def main():
    tree, out = sys.argv[1], sys.argv[2]
    utils = open(f'{tree}/{UTILS}').read()
    priv = open(f'{tree}/{PRIV}').read()

    parts = [PRELUDE.format(tree=tree)]
    for type_name in PRIV_TYPES:
        match = re.search(r'typedef struct\s*\{[^{}]*\}\s*' + type_name + r'\s*;', priv)
        if not match:
            sys.exit(f'extract: type {type_name} not found in {PRIV}')
        parts.append(match.group(0) + '\n')
    match = re.search(r'struct wifiCountryEnumStrMap\s*\{[^{}]*\}\s*;', priv)
    if not match:
        sys.exit(f'extract: struct wifiCountryEnumStrMap not found in {PRIV}')
    parts.append(match.group(0) + '\n\n')

    spans = []
    for name in REQUIRED + OPTIONAL:
        span = find_definition(utils, name)
        if span is None:
            if name in REQUIRED:
                sys.exit(f'extract: {name} not found in {UTILS}')
            continue
        spans.append((span, name))
    for (start, end), name in sorted(spans):  # source order: helpers precede their users
        parts.append(f'/* --- {name} ({UTILS}) --- */\n{utils[start:end]}\n\n')

    with open(out, 'w') as out_file:
        out_file.write(''.join(parts))


if __name__ == '__main__':
    main()
