name: Build Check

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - name: "Raspberry Pi"
            makefile_path: "build/linux/rpi/makefile"
          - name: "Banana Pi R4"
            makefile_path: "build/linux/bpi/makefile"
      fail-fast: false

    name: Build for ${{ matrix.platform.name }}

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        path: 'rdk-wifi-hal'

    - name: Clone unified-wifi-mesh repository
      run: |
        mkdir -p easymesh_project
        git clone https://github.com/rdkcentral/OneWifi.git easymesh_project/OneWifi
        git clone https://github.com/rdkcentral/unified-wifi-mesh.git easymesh_project/unified-wifi-mesh

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential \
                                cmake \
                                python3 \
                                python3-pip \
                                git \
                                vim \
                                libev-dev \
                                libjansson-dev \
                                zlib1g-dev \
                                libnl-3-dev \
                                libnl-genl-3-dev \
                                libnl-route-3-dev \
                                libavro-dev \
                                libcjson1 libcjson-dev \
                                libssl-dev \
                                uuid-dev \
                                libmysqlcppconn-dev \
                                libreadline-dev \
                                iptables \
                                mariadb-server \
                                gnupg \
                                file \
                                golang

    - name: Setup OneWiFi for ${{ matrix.platform.name }}
      working-directory: easymesh_project/OneWifi
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        make -f ${{ matrix.platform.makefile_path }} setup
        cd ..
        rm -rf rdk-wifi-hal
        mv ../rdk-wifi-hal .
      env:
        GITHUB_ACTOR: ${{ github.actor }}

    - name: Build OneWiFi for ${{ matrix.platform.name }}
      working-directory: easymesh_project/OneWifi
      run: |
        make -f ${{ matrix.platform.makefile_path }} all
